export const humanoid = {
  head: ["neck", "lEye", "rEye", "nose", "jaw", "tongue"],
  lEye: ["head"],
  rEye: ["head"],
  nose: ["head"],
  jaw: ["head"],
  tongue: ["head"],
  neck: ["torso"],
  torso: ["neck", "abdomen", "lArm", "rArm"],
  lArm: ["torso"],
  rArm: ["torso"],
  abdomen: ["lLeg", "rLeg"],
  lLeg: ["abdomen"],
  rLeg: ["abdomen"],
};
